spring:
  profiles:
#    active: @profileActive@
    active: cloud
#    active: prod

mybatis:
  type-aliases-package: com.ooad.xproject.dao
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true